name: ROS Timetable Check
on:
  push:
    branches-ignore:
      - master
jobs:
    ci-test:
        name: Test if Mergeable with Master Branch
        runs-on: ubuntu-latest
        container:
            image: artemisbeta/railwayopsim-ci:latest
            env:
                DEBIAN_FRONTEND : noninteractive
                LANG : 'en_GB.UTF-8' 
                LANGUAGE : 'en_GB:en' 
                LC_ALL : 'en_GB.UTF-8'
        
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            
            - name: Retrieve Master
              run: |
                   git fetch origin master
                   git checkout master
                   git checkout ${{ steps.extract_branch.outputs.branch }}

            - name: Run MR Merge Script
              run: git_merge_ttb ${{ steps.extract_branch.outputs.branch }} --soft --ttb-path Program_Timetables